apiVersion: apps/v1
kind: Deployment
metadata:
  name: morseip-deployment
spec:
  selector:
    matchLabels:
      app: morseip
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: morseip
    spec:
      containers:
      - name: morseip
        image: gnetanel/helloworld:1.0
        ports:
        - containerPort: 80

